export { DashboardView } from './DashboardView'
export { FeedsView } from './FeedsView'
export { ArticlesView } from './ArticlesView'
export { FavoritesView } from './FavoritesView'
export { CategoriesView } from './CategoriesView'
export { default as StatisticsView } from './StatisticsView'
